package uk.gov.communities.prsdb.webapp.models.viewModels.emailModels

interface EmailTemplateModel {
    val templateId: EmailTemplateId

    fun toHashMap(): HashMap<String, String>
}

enum class EmailTemplateId {
    LOCAL_AUTHORITY_INVITATION_EMAIL,
    LOCAL_AUTHORITY_INVITATION_CANCELLATION_EMAIL,
    LOCAL_AUTHORITY_ADMIN_INVITATION_EMAIL,
    LANDLORD_REGISTRATION_CONFIRMATION_EMAIL,
    PROPERTY_REGISTRATION_CONFIRMATION,
    PROPERTY_DEREGISTRATION_CONFIRMATION,
    LANDLORD_NO_PROPERTIES_DEREGISTRATION_CONFIRMATION,
    LANDLORD_WITH_PROPERTIES_DEREGISTRATION_CONFIRMATION,
    FULL_PROPERTY_COMPLIANCE_CONFIRMATION,
    PARTIAL_PROPERTY_COMPLIANCE_CONFIRMATION,
    VIRUS_SCAN_UNSUCCESSFUL,
    PROPERTY_UPDATE_CONFIRMATION,
    LANDLORD_UPDATE_CONFIRMATION,
}
