package uk.gov.communities.prsdb.webapp.models.viewModels.emailModels

interface EmailTemplateModel {
    val template: EmailTemplate

    fun toHashMap(): HashMap<String, String>
}

enum class EmailTemplate {
    LOCAL_AUTHORITY_INVITATION_EMAIL,
    LOCAL_AUTHORITY_INVITATION_CANCELLATION_EMAIL,
    LOCAL_AUTHORITY_ADMIN_INVITATION_EMAIL,
    LANDLORD_REGISTRATION_CONFIRMATION_EMAIL,
    PROPERTY_REGISTRATION_CONFIRMATION,
    PROPERTY_DEREGISTRATION_CONFIRMATION,
    LANDLORD_NO_PROPERTIES_DEREGISTRATION_CONFIRMATION,
    LANDLORD_WITH_PROPERTIES_DEREGISTRATION_CONFIRMATION,
    FULL_PROPERTY_COMPLIANCE_CONFIRMATION,
    PARTIAL_PROPERTY_COMPLIANCE_CONFIRMATION,
    VIRUS_SCAN_UNSUCCESSFUL,
    PROPERTY_UPDATE_CONFIRMATION,
    LANDLORD_UPDATE_CONFIRMATION,
    GIVE_FEEDBACK_LATER,
    BETA_FEEDBACK_EMAIL,
    UPDATE_GAS_SAFETY_INFORMATION_CONFIRMATION_EMAIL,
    UPDATE_GAS_SAFETY_EXPIRED_CONFIRMATION_EMAIL,
    UPDATE_ELECTRICAL_INFORMATION_CONFIRMATION_EMAIL,
    UPDATE_ELECTRICAL_INFORMATION_EXPIRED_CONFIRMATION_EMAIL,
    UPDATE_EPC_CONFIRMATION_EMAIL,
    UPDATE_EPC_LOW_RATING_CONFIRMATION_EMAIL,
    UPDATE_EPC_EXPIRED_CONFIRMATION_EMAIL,
    UPDATE_EPC_REMOVED_MEES_CONFIRMATION_EMAIL,
    UPDATE_EPC_NO_EPC_CONFIRMATION_EMAIL,
}
