version: '3.9'

services:
  postgres:
    image: postgres:16.4-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=notarealpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=prsdblocal
    volumes:
      - type: bind
        source: ./src/main/resources/data/local_authorities/addressbase-local-custodian-codes.csv
        target: /data/addressbase-local-custodian-codes.csv
  redis:
    image: redis:7.4-alpine
    restart: always
    ports:
      - "6379:6379"
    command: /bin/sh -c "redis-server --requirepass notarealpassword"