package uk.gov.communities.prsdb.webapp.forms.steps

import uk.gov.communities.prsdb.webapp.constants.FILE_UPLOAD_URL_SUBSTRING

enum class PropertyComplianceStepId(
    override val urlPathSegment: String,
    override val groupIdentifier: PropertyComplianceGroupIdentifier,
    override val isCheckYourAnswersStepId: Boolean = false,
) : GroupedUpdateStepId<PropertyComplianceGroupIdentifier> {
    CheckComplianceExists("check-property-exists", PropertyComplianceGroupIdentifier.GasSafety),
    GasSafety("gas-safety-certificate", PropertyComplianceGroupIdentifier.GasSafety),
    UpdateGasSafety("update-gas-safety-certificate", PropertyComplianceGroupIdentifier.GasSafety),
    GasSafetyIssueDate("gas-safety-certificate-issue-date", PropertyComplianceGroupIdentifier.GasSafety),
    GasSafetyEngineerNum("gas-safety-certificate-engineer-number", PropertyComplianceGroupIdentifier.GasSafety),
    GasSafetyUpload("gas-safety-certificate-$FILE_UPLOAD_URL_SUBSTRING", PropertyComplianceGroupIdentifier.GasSafety),
    GasSafetyUploadConfirmation("gas-safety-certificate-upload-confirmation", PropertyComplianceGroupIdentifier.GasSafety),
    GasSafetyOutdated("gas-safety-certificate-outdated", PropertyComplianceGroupIdentifier.GasSafety),
    GasSafetyExemption("gas-safety-certificate-exemption", PropertyComplianceGroupIdentifier.GasSafety),
    GasSafetyExemptionReason("gas-safety-certificate-exemption-reason", PropertyComplianceGroupIdentifier.GasSafety),
    GasSafetyExemptionOtherReason("gas-safety-certificate-exemption-other-reason", PropertyComplianceGroupIdentifier.GasSafety),
    GasSafetyExemptionConfirmation("gas-safety-certificate-exemption-confirmation", PropertyComplianceGroupIdentifier.GasSafety),
    GasSafetyExemptionMissing("gas-safety-certificate-exemption-missing", PropertyComplianceGroupIdentifier.GasSafety),
    GasSafetyUpdateCheckYourAnswers("gas-safety-certificate-check-your-answers", PropertyComplianceGroupIdentifier.GasSafety, true),
    EICR("eicr", PropertyComplianceGroupIdentifier.Eicr),
    UpdateEICR("update-eicr", PropertyComplianceGroupIdentifier.Eicr),
    EicrIssueDate("eicr-issue-date", PropertyComplianceGroupIdentifier.Eicr),
    EicrUpload("eicr-$FILE_UPLOAD_URL_SUBSTRING", PropertyComplianceGroupIdentifier.Eicr),
    EicrUploadConfirmation("eicr-upload-confirmation", PropertyComplianceGroupIdentifier.Eicr),
    EicrOutdated("eicr-outdated", PropertyComplianceGroupIdentifier.Eicr),
    EicrExemption("eicr-exemption", PropertyComplianceGroupIdentifier.Eicr),
    EicrExemptionReason("eicr-exemption-reason", PropertyComplianceGroupIdentifier.Eicr),
    EicrExemptionOtherReason("eicr-exemption-other-reason", PropertyComplianceGroupIdentifier.Eicr),
    EicrExemptionConfirmation("eicr-exemption-confirmation", PropertyComplianceGroupIdentifier.Eicr),
    EicrExemptionMissing("eicr-exemption-missing", PropertyComplianceGroupIdentifier.Eicr),
    UpdateEicrCheckYourAnswers("eicr-check-your-answers", PropertyComplianceGroupIdentifier.Eicr, true),
    UpdateEpc("update-epc", PropertyComplianceGroupIdentifier.Epc),
    EPC("epc", PropertyComplianceGroupIdentifier.Epc),
    EpcNotAutoMatched("epc-not-automatched", PropertyComplianceGroupIdentifier.Epc),
    CheckAutoMatchedEpc("check-auto-matched-epc", PropertyComplianceGroupIdentifier.Epc),
    CheckMatchedEpc("check-matched-epc", PropertyComplianceGroupIdentifier.Epc),
    EpcLookup("epc-lookup", PropertyComplianceGroupIdentifier.Epc),
    EpcNotFound("epc-not-found", PropertyComplianceGroupIdentifier.Epc),
    EpcSuperseded("epc-superseded", PropertyComplianceGroupIdentifier.Epc),
    EpcExpiryCheck("epc-expiry-check", PropertyComplianceGroupIdentifier.Epc),
    EpcExpired("epc-expired", PropertyComplianceGroupIdentifier.Epc),
    EpcMissing("epc-missing", PropertyComplianceGroupIdentifier.Epc),
    EpcExemptionReason("epc-exemption-reason", PropertyComplianceGroupIdentifier.Epc),
    EpcExemptionConfirmation("epc-exemption-confirmation", PropertyComplianceGroupIdentifier.Epc),
    MeesExemptionCheck("mees-exemption-check", PropertyComplianceGroupIdentifier.Epc),
    MeesExemptionReason("mees-exemption-reason", PropertyComplianceGroupIdentifier.Epc),
    MeesExemptionConfirmation("mees-exemption-confirmation", PropertyComplianceGroupIdentifier.Epc),
    LowEnergyRating("low-energy-rating", PropertyComplianceGroupIdentifier.Epc),
    UpdateEpcCheckYourAnswers("epc-check-your-answers", PropertyComplianceGroupIdentifier.Epc, true),
    FireSafetyDeclaration("fire-safety-declaration", PropertyComplianceGroupIdentifier.FireSafety),
    FireSafetyRisk("fire-safety-risk", PropertyComplianceGroupIdentifier.FireSafety),
    KeepPropertySafe("keep-property-safe", PropertyComplianceGroupIdentifier.KeepPropertySafe),
    ResponsibilityToTenants("responsibility-to-tenants", PropertyComplianceGroupIdentifier.ResponsibilityToTenants),
    CheckAndSubmit("check-and-submit", PropertyComplianceGroupIdentifier.CheckAndSubmit),
}

enum class PropertyComplianceGroupIdentifier {
    GasSafety,
    Eicr,
    Epc,
    FireSafety,
    KeepPropertySafe,
    ResponsibilityToTenants,
    CheckAndSubmit,
}
