spring:
  application:
    name: 'prsdb-webapp'

  datasource:
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: false

  data:
    redis:
      host: ${ELASTICACHE_URL}
      port: ${ELASTICACHE_PORT}
      password: ${ELASTICACHE_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          one-login:
            client-id: ${ONE_LOGIN_CLIENT_ID}
            client-authentication-method: private_key_jwt
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          one-login:
            issuer-uri: ${ONE_LOGIN_ISSUER_URL}

one-login:
  jwt:
    public.key: ${ONE_LOGIN_PUBLIC_KEY}
    private.key: ${ONE_LOGIN_PRIVATE_KEY}

notify:
  api-key: ${EMAILNOTIFICATIONS_APIKEY}

os-places:
  api-key: ${OS_PLACES_API_KEY}
  base-url: https://api.os.uk/search/places/v1

server:
  error:
    path: /error