features:
  feature-flags:
    - name: "failover-test-endpoints"
      enabled: true
      expiry-date: "2026-12-31"
    - name: "joint-landlords"
      enabled: true
      expiry-date: "2026-12-31"
    - name: "subject-identifier-page"
      enabled: true
      expiry-date: "2027-03-30"
    - name: "compliance-actions-may2026-redesign"
      enabled: false
      expiry-date: "2026-12-31"
      release: "private-beta-release-2"
    - name: "pdjb-1097-organisation-landlord-registration"
      enabled: true
      expiry-date: "2026-12-31"
  releases:
    - name: "private-beta-release-2"
      enabled: true
