features:
  overrides-enabled: true
  feature-flags:
    - name: "failover-test-endpoints"
      enabled: true
      expiry-date: "2026-12-31"
    - name: "subject-identifier-page"
      enabled: true
      expiry-date: "2027-03-30"
    - name: "pdjb-1097-organisation-landlord-registration"
      enabled: true
      expiry-date: "2026-12-31"
    - name: "pdjb-939-property-registration-restructure-and-skipping"
      enabled: false
      expiry-date: "2026-12-31"
    - name: "pdjb-1053-dashboard-nav-link"
      enabled: false
      expiry-date: "2026-12-31"
    - name: "pdjb-1022-delegate-to-letting-agent"
      enabled: false
      expiry-date: "2026-12-31"
