spring:
  application:
    name: 'prsdb-webapp'

  datasource:
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

    hikari:
      connection-init-sql: SET pg_trgm.word_similarity_threshold = 0.2

    jpa:
      hibernate:
        ddl-auto: validate
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      defer-datasource-initialization: true

  flyway:
    enabled: true
    locations: classpath:db/migrations
    validate-on-migrate: true

  sql:
    init:
      mode: always
      platform: ${ENVIRONMENT_NAME}
      continue-on-error: true

  data:
    redis:
      host: ${ELASTICACHE_URL}
      port: ${ELASTICACHE_PORT}
      password: ${ELASTICACHE_PASSWORD}

  mvc.format.date: "d MMMM yyyy"

  thymeleaf:
    render-hidden-markers-before-checkboxes: true

one-login:
  jwt:
    public.key: ${ONE_LOGIN_PUBLIC_KEY}
    private.key: ${ONE_LOGIN_PRIVATE_KEY}
  did.uri: https://identity.integration.account.gov.uk/.well-known/did.json

notify:
  api-key: ${EMAILNOTIFICATIONS_APIKEY}

os-places:
  api-key: ${OS_PLACES_API_KEY}
  base-url: https://api.os.uk/search/places/v1

server:
  error:
    path: /error

---

spring:
  config:
    activate:
      on-profile: default

  security:
    oauth2:
      client:
        registration:
          one-login:
            client-id: ${ONE_LOGIN_CLIENT_ID}
            client-authentication-method: private_key_jwt
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          one-login:
            issuer-uri: ${ONE_LOGIN_ISSUER_URL}
