create table one_login_user
(
    created_date       timestamp(6),
    last_modified_date timestamp(6),
    email              varchar(255) not null,
    id                 varchar(255) not null,
    name               varchar(255) not null,
    primary key (id)
);
create table landlord_user
(
    created_date       timestamp(6),
    date_of_birth      timestamp(6) not null,
    id                 bigint generated by default as identity,
    last_modified_date timestamp(6),
    phone_number       varchar(255) not null,
    subject_identifier varchar(255) not null unique,
    primary key (id)
);
alter table if exists landlord_user
    add constraint FK_LANDLORD_1L_USER foreign key (subject_identifier) references one_login_user;