CREATE TABLE one_login_user
(
    created_date       TIMESTAMPTZ(6),
    last_modified_date TIMESTAMPTZ(6),
    email              VARCHAR(255) NOT NULL,
    id                 VARCHAR(255) NOT NULL,
    name               VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);
CREATE TABLE landlord_user
(
    created_date       TIMESTAMPTZ(6),
    date_of_birth      TIMESTAMPTZ(6) not null,
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    last_modified_date TIMESTAMPTZ(6),
    phone_number       VARCHAR(255)   NOT NULL,
    subject_identifier VARCHAR(255)   NOT NULL UNIQUE,
    PRIMARY KEY (id)
);
CREATE TABLE local_authority_user
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_date       TIMESTAMPTZ(6),
    last_modified_date TIMESTAMPTZ(6),
    subject_identifier VARCHAR(255)   NOT NULL UNIQUE,
    is_manager         BOOLEAN,
    local_authority_id INT,
    PRIMARY KEY (id)
);
CREATE TABLE local_authority
(
    id                 INT GENERATED BY DEFAULT AS IDENTITY,
    created_date       TIMESTAMPTZ(6),
    last_modified_date TIMESTAMPTZ(6),
    name               VARCHAR(255),
    PRIMARY KEY (id)
);
ALTER TABLE IF EXISTS landlord_user
    ADD CONSTRAINT FK_LANDLORD_1L_USER FOREIGN KEY (subject_identifier) REFERENCES one_login_user;
ALTER TABLE IF EXISTS local_authority_user
    ADD CONSTRAINT FK_LA_USER_LA FOREIGN KEY (local_authority_id) REFERENCES local_authority;
ALTER TABLE IF EXISTS local_authority_user
    ADD CONSTRAINT FK_LA_USER_1L_USER FOREIGN KEY (subject_identifier) REFERENCES one_login_user;
