CREATE TABLE reminder_email_sent (
    id                              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_reminder_email_sent_date   TIMESTAMPTZ(6)  DEFAULT current_timestamp NOT NULL,
    entity_type                     SMALLINT        NOT NULL,
    entity_id                       BIGINT          NOT NULL
);
