CREATE TABLE joint_landlord_invitation (
    id                       BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_date             TIMESTAMPTZ(6) DEFAULT current_timestamp NOT NULL,
    token                    UUID           NOT NULL UNIQUE,
    invited_email            VARCHAR(255)   NOT NULL,
    registered_propertyid    BIGINT         NOT NULL,
    FOREIGN KEY (registered_propertyid) REFERENCES property_ownership(id)
);
