CREATE TABLE saved_journey_state
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    journey_id         VARCHAR(255)                            NOT NULL,
    serialized_state   TEXT                                    NOT NULL,
    subject_identifier VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_savedjourneystate PRIMARY KEY (id),
        CONSTRAINT uc_userJourney UNIQUE (journey_id, subject_identifier)
);

ALTER TABLE saved_journey_state
    ADD CONSTRAINT FK_SAVEDJOURNEYSTATE_ON_SUBJECT_IDENTIFIER FOREIGN KEY (subject_identifier) REFERENCES one_login_user (id);
