CREATE TABLE landlord
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    registration_number_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_landlord PRIMARY KEY (id)
);

CREATE TABLE registration_number
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date TIMESTAMPTZ(6),
    number       BIGINT                                  NOT NULL,
    type         SMALLINT                                NOT NULL,
    CONSTRAINT pk_registrationnumber PRIMARY KEY (id)
);

ALTER TABLE landlord
    ADD CONSTRAINT uc_landlord_registration_number UNIQUE (registration_number_id);

ALTER TABLE registration_number
    ADD CONSTRAINT uc_registrationnumber_number UNIQUE (number);

ALTER TABLE landlord
    ADD CONSTRAINT FK_LANDLORD_REG_NUM FOREIGN KEY (registration_number_id) REFERENCES registration_number (id);