CREATE TABLE reminder_email_sent (
    id                              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_reminder_email_sent_date   TIMESTAMPTZ(6)  DEFAULT current_timestamp NOT NULL
);

ALTER TABLE saved_journey_state
    ADD COLUMN reminder_email_sent_id BIGINT UNIQUE;

ALTER TABLE saved_journey_state
    ADD CONSTRAINT fk_saved_journey_state_reminder_email
        FOREIGN KEY (reminder_email_sent_id)
            REFERENCES reminder_email_sent(id);
