CREATE TABLE one_login_user (
    id           VARCHAR(255)   PRIMARY KEY,
    created_date TIMESTAMPTZ(6) DEFAULT current_timestamp NOT NULL
);

CREATE TABLE local_authority_invitation (
    id                    BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_date          TIMESTAMPTZ(6) DEFAULT current_timestamp NOT NULL,
    token                 UUID           NOT NULL UNIQUE,
    invited_email         VARCHAR(255)   NOT NULL,
    invited_as_admin      BOOLEAN        DEFAULT false NOT NULL,
    inviting_authority_id INTEGER        NOT NULL,
    FOREIGN KEY (inviting_authority_id) REFERENCES local_authority
);

CREATE TABLE local_authority_user (
    id                          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_date                TIMESTAMPTZ(6)  DEFAULT current_timestamp NOT NULL,
    last_modified_date          TIMESTAMPTZ(6),
    subject_identifier          VARCHAR(255)    NOT NULL UNIQUE,
    is_manager                  BOOLEAN         DEFAULT false NOT NULL,
    name                        VARCHAR(255)    NOT NULL,
    email                       VARCHAR(255)    NOT NULL,
    local_authority_id          INTEGER         NOT NULL,
    has_accepted_privacy_notice BOOLEAN         DEFAULT false NOT NULL,
    FOREIGN KEY (subject_identifier) REFERENCES one_login_user,
    FOREIGN KEY (local_authority_id) REFERENCES local_authority
);

CREATE TABLE system_operator (
    id                 BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_date       TIMESTAMPTZ(6)  DEFAULT current_timestamp NOT NULL,
    last_modified_date TIMESTAMPTZ(6),
    subject_identifier VARCHAR(255)    NOT NULL UNIQUE,
    FOREIGN KEY (subject_identifier) REFERENCES one_login_user
);

CREATE TABLE passcode (
    passcode           VARCHAR(255)    PRIMARY KEY,
    created_date       TIMESTAMPTZ(6)  DEFAULT current_timestamp NOT NULL,
    last_modified_date TIMESTAMPTZ(6),
    local_authority_id INTEGER         NOT NULL,
    subject_identifier VARCHAR(255)    UNIQUE,
    FOREIGN KEY (local_authority_id) REFERENCES local_authority,
    FOREIGN KEY (subject_identifier) REFERENCES one_login_user
);

CREATE TABLE form_context (
    id                 BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_date       TIMESTAMPTZ(6)  DEFAULT current_timestamp NOT NULL,
    last_modified_date TIMESTAMPTZ(6),
    journey_type       SMALLINT        NOT NULL,
    context            TEXT            NOT NULL,
    subject_identifier VARCHAR(255)    NOT NULL,
    FOREIGN KEY (subject_identifier) REFERENCES one_login_user
);

CREATE TABLE registration_number (
    id           BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_date TIMESTAMPTZ(6) DEFAULT current_timestamp NOT NULL,
    number       BIGINT         NOT NULL UNIQUE,
    type         SMALLINT       NOT NULL
);

CREATE TABLE landlord (
    id                           BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_date                 TIMESTAMPTZ(6)  DEFAULT current_timestamp NOT NULL,
    last_modified_date           TIMESTAMPTZ(6),
    subject_identifier           VARCHAR(255)    NOT NULL UNIQUE,
    name                         VARCHAR(255)    NOT NULL,
    email                        VARCHAR(255)    NOT NULL,
    phone_number                 VARCHAR(255)    NOT NULL,
    address_id                   BIGINT          NOT NULL,
    country_of_residence         VARCHAR(255)    NOT NULL,
    non_england_or_wales_address VARCHAR(1000),
    date_of_birth                DATE,
    registration_number_id       BIGINT          NOT NULL UNIQUE,
    is_active                    BOOLEAN         DEFAULT false NOT NULL,
    is_verified                  BOOLEAN         DEFAULT false NOT NULL,
    has_accepted_privacy_notice  BOOLEAN         DEFAULT false NOT NULL,
    has_responded_to_feedback    BOOLEAN         DEFAULT false NOT NULL,
    FOREIGN KEY (subject_identifier) REFERENCES one_login_user,
    FOREIGN KEY (address_id) REFERENCES address,
    FOREIGN KEY (registration_number_id) REFERENCES registration_number
);

CREATE TABLE property (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_date        TIMESTAMPTZ(6)  DEFAULT current_timestamp NOT NULL,
    last_modified_date  TIMESTAMPTZ(6),
    status              SMALLINT        NOT NULL,
    is_active           BOOLEAN         DEFAULT false NOT NULL,
    property_build_type SMALLINT        NOT NULL,
    address_id          BIGINT          NOT NULL UNIQUE,
    FOREIGN KEY (address_id) REFERENCES address
);

CREATE TABLE license (
    id                 BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_date       TIMESTAMPTZ(6)  DEFAULT current_timestamp NOT NULL,
    last_modified_date TIMESTAMPTZ(6),
    license_type       SMALLINT        NOT NULL,
    license_number     VARCHAR(255)    NOT NULL
);

CREATE TABLE property_ownership (
    id                            BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_date                  TIMESTAMPTZ(6)  DEFAULT current_timestamp NOT NULL,
    last_modified_date            TIMESTAMPTZ(6),
    is_active                     BOOLEAN         DEFAULT false NOT NULL,
    tenancy_start_date            DATE,
    occupancy_type                SMALLINT        NOT NULL,
    ownership_type                SMALLINT        NOT NULL,
    current_num_households        INTEGER         DEFAULT 0 NOT NULL,
    current_num_tenants           INTEGER         DEFAULT 0 NOT NULL,
    registration_number_id        BIGINT          NOT NULL UNIQUE,
    primary_landlord_id           BIGINT          NOT NULL,
    property_id                   BIGINT          NOT NULL,
    license_id                    BIGINT          UNIQUE,
    incomplete_compliance_form_id BIGINT          UNIQUE,
    FOREIGN KEY (registration_number_id) REFERENCES registration_number,
    FOREIGN KEY (primary_landlord_id) REFERENCES landlord,
    FOREIGN KEY (property_id) REFERENCES property,
    FOREIGN KEY (license_id) REFERENCES license,
    FOREIGN KEY (incomplete_compliance_form_id) REFERENCES form_context
);

CREATE UNIQUE INDEX uc_propertyownership_active_property_id ON property_ownership USING btree (property_id) WHERE is_active;

CREATE TABLE file_upload (
    id                 BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_date       TIMESTAMPTZ(6)  DEFAULT current_timestamp NOT NULL,
    last_modified_date TIMESTAMPTZ(6),
    status             SMALLINT        NOT NULL,
    object_key         VARCHAR(255)    NOT NULL,
    e_tag              VARCHAR(255)    NOT NULL,
    version_id         VARCHAR(255),
    extension          VARCHAR(255)    NOT NULL,
    CONSTRAINT uc_fileupload_s3_object UNIQUE (object_key, e_tag, version_id)
);

CREATE TABLE certificate_upload (
    id                    BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_date          TIMESTAMPTZ(6)  DEFAULT current_timestamp NOT NULL,
    last_modified_date    TIMESTAMPTZ(6),
    category              SMALLINT        NOT NULL,
    property_ownership_id BIGINT          NOT NULL,
    file_upload_id        BIGINT          NOT NULL UNIQUE,
    FOREIGN KEY (property_ownership_id) REFERENCES property_ownership,
    FOREIGN KEY (file_upload_id) REFERENCES file_upload
);

CREATE TABLE property_compliance (
    id                                        BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_date                              TIMESTAMPTZ(6)  DEFAULT current_timestamp NOT NULL,
    last_modified_date                        TIMESTAMPTZ(6),
    property_ownership_id                     BIGINT          NOT NULL UNIQUE,
    gas_safety_upload_id                      BIGINT          UNIQUE,
    gas_safety_cert_issue_date                DATE,
    gas_safety_cert_engineer_num              VARCHAR(255),
    gas_safety_cert_exemption_reason          SMALLINT,
    gas_safety_cert_exemption_other_reason    VARCHAR(255),
    eicr_upload_id                            BIGINT          UNIQUE,
    eicr_issue_date                           DATE,
    eicr_exemption_reason                     SMALLINT,
    eicr_exemption_other_reason               VARCHAR(255),
    epc_url                                   VARCHAR(255),
    epc_expiry_date                           DATE,
    tenancy_started_before_epc_expiry         BOOLEAN,
    epc_energy_rating                         VARCHAR(255),
    epc_exemption_reason                      SMALLINT,
    epc_mees_exemption_reason                 SMALLINT,
    has_fire_safety_declaration               BOOLEAN         DEFAULT true NOT NULL,
    has_keep_property_safe_declaration        BOOLEAN         DEFAULT true NOT NULL,
    has_responsibility_to_tenants_declaration BOOLEAN         DEFAULT true NOT NULL,
    FOREIGN KEY (property_ownership_id) REFERENCES property_ownership,
    FOREIGN KEY (gas_safety_upload_id) REFERENCES file_upload,
    FOREIGN KEY (eicr_upload_id) REFERENCES file_upload
);

CREATE VIEW local_authority_user_or_invitation AS
    SELECT u.id,
           u.name,
           u.is_manager,
           u.local_authority_id,
           'local_authority_user' AS entity_type
    FROM local_authority_user u
UNION ALL
    SELECT i.id,
           i.invited_email AS name,
           i.invited_as_admin AS is_manager,
           i.inviting_authority_id AS local_authority_id,
           'local_authority_invitation' AS entity_type
    FROM local_authority_invitation i;

CREATE VIEW landlord_with_listed_property_count AS
SELECT l.id AS landlord_id, count(po.primary_landlord_id) AS listed_property_count
FROM property_ownership po RIGHT JOIN landlord l ON (po.primary_landlord_id = l.id AND po.is_active = true)
GROUP BY l.id;

CREATE EXTENSION IF NOT EXISTS pg_trgm;
