CREATE TABLE reminder_email_sent (
    id                              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_reminder_email_sent_date   TIMESTAMPTZ(6)  DEFAULT current_timestamp NOT NULL,
    saved_journey_state_id          BIGINT,
    CONSTRAINT fk_reminder_email_saved_journey_state
        FOREIGN KEY (saved_journey_state_id)
        REFERENCES saved_journey_state(id)
        ON DELETE CASCADE,
    CONSTRAINT chk_saved_journey_state_not_null
        CHECK (saved_journey_state_id IS NOT NULL)
);
