ALTER TABLE certificate_upload
DROP
CONSTRAINT certificate_upload_file_upload_id_fkey;

ALTER TABLE certificate_upload
DROP
CONSTRAINT certificate_upload_property_ownership_id_fkey;

CREATE TABLE virus_scan_callback
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    last_modified_date    TIMESTAMP WITHOUT TIME ZONE,
    created_date          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    type                  SMALLINT                                NOT NULL,
    encoded_callback_data VARCHAR(255)                            NOT NULL,
    file_upload_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_virusscancallback PRIMARY KEY (id)
);

DROP TABLE certificate_upload CASCADE;

ALTER TABLE virus_scan_callback
    ADD CONSTRAINT FK_VIRUSSCANCALLBACK_ON_FILE_UPLOAD FOREIGN KEY (file_upload_id) REFERENCES file_upload (id);
