CREATE TABLE system_operator
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_date       TIMESTAMPTZ(6),
    last_modified_date TIMESTAMPTZ(6),
    subject_identifier VARCHAR(255)   NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS system_operator
    ADD CONSTRAINT FK_SYSTEM_OPERATOR_1L_USER FOREIGN KEY (subject_identifier) REFERENCES one_login_user;