ALTER TABLE IF EXISTS passcode
    DROP CONSTRAINT IF EXISTS FK_PASSCODE_1L_USER CASCADE;
ALTER TABLE IF EXISTS passcode
    DROP CONSTRAINT IF EXISTS FK_PASSCODE_LA CASCADE;
ALTER TABLE IF EXISTS passcode
    DROP CONSTRAINT IF EXISTS passcode_pkey CASCADE;
ALTER TABLE IF EXISTS passcode
    RENAME COLUMN id TO passcode;
ALTER TABLE IF EXISTS passcode ADD PRIMARY KEY (passcode);
ALTER TABLE IF EXISTS passcode
    ADD CONSTRAINT FK_PASSCODE_LA FOREIGN KEY (local_authority_id) REFERENCES local_authority;
ALTER TABLE IF EXISTS passcode
    ADD CONSTRAINT FK_PASSCODE_1L_USER FOREIGN KEY (subject_identifier) REFERENCES one_login_user;
