CREATE TABLE property_compliance
(
    id                                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    last_modified_date                     TIMESTAMPTZ(6),
    created_date                           TIMESTAMPTZ(6),
    property_ownership_id                  BIGINT                                  NOT NULL,
    gas_safety_cert_s3_key                 VARCHAR(255),
    gas_safety_cert_issue_date             DATE,
    gas_safety_cert_engineer_num           VARCHAR(255),
    gas_safety_cert_exemption_reason       SMALLINT,
    gas_safety_cert_exemption_other_reason VARCHAR(255),
    eicr_s3_key                            VARCHAR(255),
    eicr_issue_date                        DATE,
    eicr_exemption_reason                  SMALLINT,
    eicr_exemption_other_reason            VARCHAR(255),
    epc_url                                VARCHAR(255),
    epc_expiry_date                        DATE,
    epc_energy_rating                      VARCHAR(255),
    epc_exemption_reason                   SMALLINT,
    epc_mees_exemption_reason              SMALLINT,
    has_fire_safety_declaration            BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_propertycompliance PRIMARY KEY (id)
);

ALTER TABLE property_compliance
    ADD CONSTRAINT uc_propertycompliance_property_ownership UNIQUE (property_ownership_id);

ALTER TABLE property_compliance
    ADD CONSTRAINT FK_PROPERTY_COMPLIANCE_PROPERTY_OWNERSHIP FOREIGN KEY (property_ownership_id) REFERENCES property_ownership (id);