CREATE TABLE form_context
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMPTZ(6),
    last_modified_date TIMESTAMPTZ(6),
    journey_type       SMALLINT                                NOT NULL,
    context            TEXT                                    NOT NULL,
    subject_identifier VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_formcontext PRIMARY KEY (id)
);

ALTER TABLE form_context
    ADD CONSTRAINT FK_FORM_CONTEXT_1L_USER FOREIGN KEY (subject_identifier) REFERENCES one_login_user (id);