CREATE TABLE certificate_upload
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    last_modified_date    TIMESTAMPTZ(6),
    created_date          TIMESTAMPTZ(6),
    category              SMALLINT,
    property_ownership_id BIGINT,
    file_upload_id        BIGINT,
    CONSTRAINT pk_certificateupload PRIMARY KEY (id)
);

ALTER TABLE certificate_upload
    ADD CONSTRAINT uc_certificateupload_file_upload UNIQUE (file_upload_id);

ALTER TABLE certificate_upload
    ADD CONSTRAINT FK_CERTIFICATEUPLOAD_ON_FILE_UPLOAD FOREIGN KEY (file_upload_id) REFERENCES file_upload (id);

ALTER TABLE certificate_upload
    ADD CONSTRAINT FK_CERTIFICATEUPLOAD_ON_PROPERTY_OWNERSHIP FOREIGN KEY (property_ownership_id) REFERENCES property_ownership (id);
