CREATE TABLE local_authority_user_invitation
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    invited_email_address   VARCHAR(255) NOT NULL,
    local_authority_id      INT NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS local_authority_user
    ADD CONSTRAINT FK_LA_USER_INVITATION_LA FOREIGN KEY (local_authority_id) REFERENCES local_authority;