CREATE TABLE local_authority_invitation
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date          TIMESTAMP WITHOUT TIME ZONE,
    token                 UUID                                    NOT NULL,
    invited_email         VARCHAR(255)                            NOT NULL,
    inviting_authority_id INTEGER                                 NOT NULL,
    CONSTRAINT pk_localauthorityinvitation PRIMARY KEY (id)
);

ALTER TABLE local_authority_invitation
    ADD CONSTRAINT uc_localauthorityinvitation_token UNIQUE (token);

ALTER TABLE local_authority_invitation
    ADD CONSTRAINT FK_LA_INVITATION_LA FOREIGN KEY (inviting_authority_id) REFERENCES local_authority (id);