CREATE TABLE landlord_access_link (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    landlord_id BIGINT NOT NULL REFERENCES landlord(id),
    subject_identifier VARCHAR(255) NOT NULL REFERENCES prsdb_user(id),
    created_date TIMESTAMPTZ(6) DEFAULT current_timestamp NOT NULL,
    UNIQUE (landlord_id, subject_identifier)
);

CREATE INDEX idx_landlord_access_link_subject ON landlord_access_link(subject_identifier);
CREATE INDEX idx_landlord_access_link_landlord ON landlord_access_link(landlord_id);
