CREATE TABLE local_authority_invite
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date          TIMESTAMP WITHOUT TIME ZONE,
    token                 UUID                                    NOT NULL,
    inviting_authority_id INTEGER                                 NOT NULL,
    CONSTRAINT pk_localauthorityinvite PRIMARY KEY (id)
);

ALTER TABLE local_authority_invite
    ADD CONSTRAINT uc_localauthorityinvite_invitingauthority UNIQUE (inviting_authority_id);

ALTER TABLE local_authority_invite
    ADD CONSTRAINT uc_localauthorityinvite_token UNIQUE (token);

ALTER TABLE local_authority_invite
    ADD CONSTRAINT FK_LA_INVITE_LA FOREIGN KEY (inviting_authority_id) REFERENCES local_authority (id);