ALTER TABLE landlordship_members
DROP
CONSTRAINT fk_lanmem_on_landlord;

ALTER TABLE landlordship_members
DROP
CONSTRAINT fk_lanmem_on_property_ownership;

CREATE TABLE ownership_link
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    landlord_id        BIGINT                                  NOT NULL,
    landlordship_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_ownershiplink PRIMARY KEY (id)
);

INSERT INTO ownership_link (landlord_id, landlordship_id) SELECT lm.landlord_id, lm.landlordship_id FROM landlordship_members lm;

ALTER TABLE ownership_link
    ADD CONSTRAINT FK_OWNERSHIPLINK_ON_LANDLORD FOREIGN KEY (landlord_id) REFERENCES landlord (id) ON DELETE CASCADE ;

ALTER TABLE ownership_link
    ADD CONSTRAINT FK_OWNERSHIPLINK_ON_LANDLORDSHIP FOREIGN KEY (landlordship_id) REFERENCES property_ownership (id) ON DELETE CASCADE ;

DROP TABLE landlordship_members CASCADE;
