-- Rename IndividualLandlord-specific columns to have individual_ prefix
ALTER TABLE landlord RENAME COLUMN subject_identifier TO individual_subject_identifier;
ALTER TABLE landlord RENAME COLUMN name TO individual_name;
ALTER TABLE landlord RENAME COLUMN email TO individual_email;
ALTER TABLE landlord RENAME COLUMN phone_number TO individual_phone_number;
ALTER TABLE landlord RENAME COLUMN address_id TO individual_address_id;
ALTER TABLE landlord RENAME COLUMN country_of_residence TO individual_country_of_residence;
ALTER TABLE landlord RENAME COLUMN non_england_or_wales_address TO individual_non_england_or_wales_address;
ALTER TABLE landlord RENAME COLUMN date_of_birth TO individual_date_of_birth;
ALTER TABLE landlord RENAME COLUMN is_active TO individual_is_active;
ALTER TABLE landlord RENAME COLUMN is_verified TO individual_is_verified;
ALTER TABLE landlord RENAME COLUMN has_accepted_privacy_notice TO individual_has_accepted_privacy_notice;
ALTER TABLE landlord RENAME COLUMN has_responded_to_feedback TO individual_has_responded_to_feedback;

-- Relax NOT NULL on IndividualLandlord-specific columns so OrganisationLandlord rows can have NULLs
ALTER TABLE landlord ALTER COLUMN individual_subject_identifier DROP NOT NULL;
ALTER TABLE landlord ALTER COLUMN individual_name DROP NOT NULL;
ALTER TABLE landlord ALTER COLUMN individual_email DROP NOT NULL;
ALTER TABLE landlord ALTER COLUMN individual_phone_number DROP NOT NULL;
ALTER TABLE landlord ALTER COLUMN individual_address_id DROP NOT NULL;
ALTER TABLE landlord ALTER COLUMN individual_country_of_residence DROP NOT NULL;
ALTER TABLE landlord ALTER COLUMN individual_is_active DROP NOT NULL;
ALTER TABLE landlord ALTER COLUMN individual_is_verified DROP NOT NULL;
ALTER TABLE landlord ALTER COLUMN individual_has_accepted_privacy_notice DROP NOT NULL;
ALTER TABLE landlord ALTER COLUMN individual_has_responded_to_feedback DROP NOT NULL;

-- Rebuild search indexes with new column names
DROP INDEX IF EXISTS landlord_details_gin_idx;
DROP INDEX IF EXISTS landlord_details_gist_idx;
CREATE INDEX landlord_details_gin_idx ON landlord USING gin (gin_landlord_details(individual_phone_number, individual_email, individual_name) gin_trgm_ops);
CREATE INDEX landlord_details_gist_idx ON landlord USING gist (gist_landlord_details(individual_phone_number, individual_email, individual_name) gist_trgm_ops(siglen=256));

-- Add OrganisationLandlord columns (all nullable)
ALTER TABLE landlord ADD COLUMN organisation_landlord_name VARCHAR(255);
ALTER TABLE landlord ADD COLUMN organisation_address_id BIGINT;
ALTER TABLE landlord ADD COLUMN organisation_email VARCHAR(255);
ALTER TABLE landlord ADD COLUMN organisation_phone_number VARCHAR(255);
ALTER TABLE landlord ADD COLUMN organisation_is_company BOOLEAN;
ALTER TABLE landlord ADD COLUMN organisation_is_charity BOOLEAN;
ALTER TABLE landlord ADD COLUMN organisation_is_trust BOOLEAN;
ALTER TABLE landlord ADD COLUMN organisation_company_number VARCHAR(255);
ALTER TABLE landlord ADD COLUMN organisation_charity_registered_with SMALLINT;
ALTER TABLE landlord ADD COLUMN organisation_charity_number VARCHAR(255);
ALTER TABLE landlord ADD COLUMN organisation_lead_trustee_name VARCHAR(255);
ALTER TABLE landlord ADD COLUMN organisation_lead_trustee_date_of_birth DATE;
ALTER TABLE landlord ADD COLUMN organisation_lead_trustee_email VARCHAR(255);
ALTER TABLE landlord ADD COLUMN organisation_lead_trustee_phone VARCHAR(255);
ALTER TABLE landlord ADD COLUMN organisation_lead_trustee_address_id BIGINT;
ALTER TABLE landlord ADD COLUMN organisation_main_contact_name VARCHAR(255);
ALTER TABLE landlord ADD COLUMN organisation_main_contact_email VARCHAR(255);
ALTER TABLE landlord ADD COLUMN organisation_main_contact_phone VARCHAR(255);

-- FK constraints for address columns
ALTER TABLE landlord ADD CONSTRAINT fk_org_landlord_address
    FOREIGN KEY (organisation_address_id) REFERENCES address(id);
ALTER TABLE landlord ADD CONSTRAINT fk_org_landlord_lead_trustee_address
    FOREIGN KEY (organisation_lead_trustee_address_id) REFERENCES address(id);

-- Create organisation_governing_body_member table
CREATE TABLE organisation_governing_body_member (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_date              TIMESTAMPTZ(6) DEFAULT current_timestamp NOT NULL,
    last_modified_date        TIMESTAMPTZ(6),
    organisation_landlord_id  BIGINT NOT NULL,
    type                      SMALLINT NOT NULL,
    name                      VARCHAR(255) NOT NULL,
    date_of_birth             DATE NOT NULL,
    address_id                BIGINT NOT NULL,
    CONSTRAINT fk_governing_body_member_org_landlord FOREIGN KEY (organisation_landlord_id) REFERENCES landlord(id) ON DELETE CASCADE,
    CONSTRAINT fk_governing_body_member_address FOREIGN KEY (address_id) REFERENCES address(id)
);
