CREATE TABLE letting_agent_access (
    id                    BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_date          TIMESTAMPTZ(6) DEFAULT current_timestamp NOT NULL,
    last_modified_date    TIMESTAMPTZ(6),
    token                 UUID           NOT NULL UNIQUE,
    invited_email         VARCHAR(255)   NOT NULL,
    property_ownership_id BIGINT         NOT NULL UNIQUE,
    hashed_password       VARCHAR(255),
    access_link           VARCHAR(255)   UNIQUE,
    FOREIGN KEY (property_ownership_id) REFERENCES property_ownership(id)
);
