ALTER TABLE organisation_landlord_user RENAME TO organisation_user;

ALTER INDEX idx_organisation_landlord_user_subject RENAME TO idx_organisation_user_subject;
ALTER INDEX idx_organisation_landlord_user_organisation_landlord RENAME TO idx_organisation_user_organisation_landlord;

ALTER TABLE organisation_user RENAME CONSTRAINT org_landlord_user_org_landlord_id_subject_identifier_key
    TO org_user_org_landlord_id_subject_identifier_key;
