CREATE TABLE organisational_landlord_invitation (
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_date                 TIMESTAMPTZ(6) DEFAULT current_timestamp NOT NULL,
    last_modified_date           TIMESTAMPTZ(6),
    token                        UUID NOT NULL UNIQUE,
    invited_email                VARCHAR(255) NOT NULL,
    organisation_landlord_id     BIGINT NOT NULL,
    inviting_organisation_name   VARCHAR(255) NOT NULL,
    role                         SMALLINT NOT NULL,
    invitation_expired_email_sent BOOLEAN NOT NULL DEFAULT FALSE,
    is_hidden                    BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_organisational_landlord_invitation_organisation_landlord
        FOREIGN KEY (organisation_landlord_id) REFERENCES landlord(id)
);

CREATE INDEX idx_organisational_landlord_invitation_organisation_landlord
    ON organisational_landlord_invitation (organisation_landlord_id);
