CREATE TABLE property
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    last_modified_date  TIMESTAMP WITHOUT TIME ZONE,
    created_date        TIMESTAMP WITHOUT TIME ZONE,
    status              SMALLINT                                NOT NULL,
    is_active           BOOLEAN                                 NOT NULL,
    property_build_type SMALLINT                                NOT NULL,
    has_gas_supply      BOOLEAN                                 NOT NULL,
    address_id          BIGINT                                  NOT NULL,
    CONSTRAINT pk_property PRIMARY KEY (id)
);

CREATE TABLE property_ownership
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    last_modified_date     TIMESTAMP WITHOUT TIME ZONE,
    created_date           TIMESTAMP WITHOUT TIME ZONE,
    is_active              BOOLEAN                                 NOT NULL,
    tenancy_start_date     TIMESTAMP WITHOUT TIME ZONE,
    occupancy_type         SMALLINT                                NOT NULL,
    landlord_type          SMALLINT                                NOT NULL,
    current_num_households INTEGER                                 NOT NULL,
    registration_number_id BIGINT                                  NOT NULL,
    property_id            BIGINT                                  NOT NULL,
    payment_id             BIGINT,
    primary_landlord_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_propertyownership PRIMARY KEY (id)
);

ALTER TABLE property
    ADD CONSTRAINT uc_property_address UNIQUE (address_id);

ALTER TABLE property_ownership
    ADD CONSTRAINT uc_propertyownership_registration_number UNIQUE (registration_number_id);

CREATE UNIQUE INDEX one_active_ownership_per_property ON property_ownership(property_id)
    WHERE is_active;

ALTER TABLE property
    ADD CONSTRAINT FK_PROPERTY_ADDRESS FOREIGN KEY (address_id) REFERENCES address (id);

ALTER TABLE property_ownership
    ADD CONSTRAINT FK_PROPERTY_OWNERSHIP_PROPERTY FOREIGN KEY (property_id) REFERENCES property (id);

ALTER TABLE property_ownership
    ADD CONSTRAINT FK_PROPERTY_OWNERSHIP_REGISTRATION_NUMBER FOREIGN KEY (registration_number_id) REFERENCES registration_number (id);

ALTER TABLE property_ownership
    ADD CONSTRAINT FK_PROPERTY_OWNERSHIP_PRIMARY_LANDLORD FOREIGN KEY (primary_landlord_id) REFERENCES landlord (id);