CREATE TABLE property
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    last_modified_date  TIMESTAMP WITHOUT TIME ZONE,
    created_date        TIMESTAMP WITHOUT TIME ZONE,
    status              SMALLINT,
    is_active           BOOLEAN                                 NOT NULL,
    property_build_type SMALLINT,
    has_gas_supply      BOOLEAN,
    address_id          BIGINT                                  NOT NULL,
    CONSTRAINT pk_property PRIMARY KEY (id)
);

CREATE TABLE property_ownership
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    last_modified_date     TIMESTAMP WITHOUT TIME ZONE,
    created_date           TIMESTAMP WITHOUT TIME ZONE,
    is_active              BOOLEAN                                 NOT NULL,
    tenancy_start_date     TIMESTAMP WITHOUT TIME ZONE,
    occupancy_type         SMALLINT,
    landlord_type          SMALLINT,
    current_num_households INTEGER                                 NOT NULL,
    registration_number_id BIGINT                                  NOT NULL,
    property_id            BIGINT                                  NOT NULL,
    payment_id             BIGINT                                  NOT NULL,
    CONSTRAINT pk_propertyownership PRIMARY KEY (id)
);

CREATE TABLE payment
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date      TIMESTAMP WITHOUT TIME ZONE,
    payment_date_time TIMESTAMP WITHOUT TIME ZONE,
    payment_amount    DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_payment PRIMARY KEY (id)
);


CREATE TABLE landlord_property_ownership
(
    landlord_id           BIGINT NOT NULL,
    property_ownership_id BIGINT NOT NULL,
    CONSTRAINT pk_landlord_property_ownership PRIMARY KEY (landlord_id, property_ownership_id)
);

ALTER TABLE property
    ADD CONSTRAINT uc_property_address UNIQUE (address_id);

ALTER TABLE property_ownership
    ADD CONSTRAINT uc_propertyownership_property UNIQUE (property_id);

ALTER TABLE property_ownership
    ADD CONSTRAINT uc_propertyownership_registration_number UNIQUE (registration_number_id);

ALTER TABLE property_ownership
    ADD CONSTRAINT FK_PROPERTYOWNERSHIP_ON_PAYMENT FOREIGN KEY (payment_id) REFERENCES payment (id);

ALTER TABLE property
    ADD CONSTRAINT FK_PROPERTY_ADDRESS FOREIGN KEY (address_id) REFERENCES address (id);

ALTER TABLE property_ownership
    ADD CONSTRAINT FK_PROPERTY_OWNERSHIP_PROPERTY FOREIGN KEY (property_id) REFERENCES property (id);

ALTER TABLE property_ownership
    ADD CONSTRAINT FK_PROPERTY_OWNERSHIP_REGISTRATION_NUMBER FOREIGN KEY (registration_number_id) REFERENCES registration_number (id);

ALTER TABLE landlord_property_ownership
    ADD CONSTRAINT fk_lanproown_on_landlord FOREIGN KEY (landlord_id) REFERENCES landlord (id);

ALTER TABLE landlord_property_ownership
    ADD CONSTRAINT fk_lanproown_on_property_ownership FOREIGN KEY (property_ownership_id) REFERENCES property_ownership (id);