CREATE TABLE license
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    last_modified_date  TIMESTAMP WITHOUT TIME ZONE,
    created_date        TIMESTAMP WITHOUT TIME ZONE,
    license_type        SMALLINT                                NOT NULL,
    license_number      VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_license PRIMARY KEY (id)
);

ALTER TABLE property_ownership
    ADD license_id              BIGINT;

ALTER TABLE property_ownership
    ADD CONSTRAINT FK_PROPERTY_OWNERSHIP_LICENSE FOREIGN KEY (license_id) REFERENCES license (id);