package uk.gov.communities.prsdb.webapp.constants.enums

enum class JourneyType {
    LANDLORD_REGISTRATION,
    LANDLORD_DEREGISTRATION,
    LOCAL_COUNCIL_USER_REGISTRATION,
    PROPERTY_REGISTRATION,
    PROPERTY_DEREGISTRATION,
    LANDLORD_DETAILS_UPDATE,
    PROPERTY_DETAILS_UPDATE,
    PROPERTY_COMPLIANCE,
    PROPERTY_COMPLIANCE_UPDATE,
}
