package uk.gov.communities.prsdb.webapp.constants

const val MAX_ENTRIES_IN_LOCAL_COUNCIL_USERS_TABLE_PAGE = 10
const val MAX_ENTRIES_IN_LANDLORDS_SEARCH_PAGE = 25

const val MAX_PAGES_IN_PROPERTIES_SEARCH = 100
const val MAX_ENTRIES_IN_PROPERTIES_SEARCH_PAGE = 25
const val MAX_ENTRIES_IN_PROPERTIES_SEARCH = MAX_PAGES_IN_PROPERTIES_SEARCH * MAX_ENTRIES_IN_PROPERTIES_SEARCH_PAGE
