package uk.gov.communities.prsdb.webapp.constants

const val UPDATE_PATH_SEGMENT = "update"
const val LANDLORD_DETAILS_PATH_SEGMENT = "landlord-details"
const val PROPERTY_DETAILS_SEGMENT = "property-details"
const val LOCAL_AUTHORITY_PATH_SEGMENT = "local-authority"
const val LANDLORD_PATH_SEGMENT = "landlord"
const val PROPERTY_PATH_SEGMENT = "property"
const val DASHBOARD_PATH_SEGMENT = "dashboard"
const val SEARCH_PATH_SEGMENT = "search"
const val REGISTERED_PROPERTIES_PATH_SEGMENT = "registered-properties"
const val CONFIRMATION_PATH_SEGMENT = "confirmation"
const val TASK_LIST_PATH_SEGMENT = "task-list"
const val PROPERTY_COMPLIANCE_PATH_SEGMENT = "provide-compliance-certificates"
const val START_PAGE_PATH_SEGMENT = "start"
const val RESUME_PAGE_PATH_SEGMENT = "resume"
const val INCOMPLETE_PROPERTIES_PATH_SEGMENT = "incomplete-properties"
const val SYSTEM_OPERATOR_PATH_SEGMENT = "system-operator"
const val INVITE_LA_ADMIN_PATH_SEGMENT = "invite-la-admin"
const val DELETE_INCOMPLETE_PROPERTY_PATH_SEGMENT = "delete-incomplete-property"
const val ADD_COMPLIANCE_INFORMATION_PATH_SEGMENT = "add-compliance-information"
