package uk.gov.communities.prsdb.webapp.constants

const val ROLE_LANDLORD = "ROLE_LANDLORD"

const val ROLE_LOCAL_COUNCIL_ADMIN = "ROLE_LOCAL_COUNCIL_ADMIN"

const val ROLE_LOCAL_COUNCIL_USER = "ROLE_LOCAL_COUNCIL_USER"

const val ROLE_SYSTEM_OPERATOR = "ROLE_SYSTEM_OPERATOR"
