name: Build and Deploy Test
on:
  push:
    branches:
      - test

jobs:
  build-and-deploy-integration:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      environment: "test"
      build-and-deploy-role: "arn:aws:iam::869935096717:role/test-push-image"
      migrations-role: "arn:aws:iam::869935096717:role/test-rds-access"
      ecr-repository: "test-webapp"
      account-id: "869935096717"
      branch: "test"
    secrets: inherit
