name: Build and Deploy - Test
on:
  push:
    branches:
      - test

jobs:
  build-and-deploy-integration:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      environment: "test"
      aws-account-id: "869935096717"
    secrets: inherit
