name: Build and Deploy - Production
on:
  push:
    branches:
      - production

jobs:
  build-and-deploy-production:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      environment: "production"
      aws-account-id: "879161327637"
    secrets: inherit
