name: Build and Deploy - Integration
on:
  push:
    branches:
      - main
      - chore/PRSD-1021-more-selective-property-address-updates

jobs:
  build-and-deploy-integration:
    name: Build and Deploy
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      environment: "integration"
      aws-account-id: "794038239680"
    secrets: inherit
