name: Build and Deploy - NFT
on:
  push:
    branches:
      - nft

jobs:
  simulator-contract-test:
    name: One Login simulator contract test
    uses: ./.github/workflows/one-login-simulator-contract-test.yml
    with:
      environment: "nft"
    secrets: inherit

  build-and-deploy-integration:
    name: Build and deploy
    needs: simulator-contract-test
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      environment: "nft"
      aws-account-id: "448120078528"
    secrets: inherit
