name: Deploy - Integration
on: workflow_dispatch

jobs:
  build-and-deploy-integration:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: "integration"
      build-and-deploy-role: "arn:aws:iam::794038239680:role/integration-push-image"
      update-ecs-role: "arn:aws:iam::794038239680:role/github-actions-terraform-admin"
      ecr-repository: "integration-webapp"
      account-id: "794038239680"
      branch: "main"
    secrets: inherit
