name: Reset Database - Test
on: workflow_dispatch

jobs:
  reset-database:
    name: Reset Database
    uses: ./.github/workflows/reset-database.yml
    with:
      environment: test
      branch: test
      aws-account-id: 869935096717
