name: Reset Database - Integration
on: workflow_dispatch

jobs:
  reset-database:
    name: Reset Database
    uses: ./.github/workflows/reset-database.yml
    with:
      environment: integration
      branch: main
      aws-account-id: 794038239680
